---
- name: Deploy RKE2
  hosts: all
  become: yes

  roles:
     - role: upgrade_machine
     - role: lablabs.rke2
       vars: 
         rke2_download_kubeconf: true
         rke2_download_kubeconf_file_name: rke2.yaml
         rke2_download_kubeconf_path: /etc/rancher/rke2